---
- name: Format EBS volume
  filesystem: fstype=ext4 dev=/dev/xvdf

- name: Edit fstab and mount the volume
  mount: name={{ mount_dir }} src=/dev/xvdf opts=noatime fstype=ext4 state=mounted

- name: Create jenkins dir
  file: path={{ jenkins_home }} mode=755 state=directory owner=jenkins

- name: Create logs dir
  file: path={{ jenkins_logs_dir }} mode=755 state=directory owner=jenkins

